### PR TITLE
Add online content badge to search results

### LINKED ISSUE #1053: Show Online content icons on search results page
Display the online content icon on search results page if digital content is available. In both grouped and all results

This is both the placement and the fact that an icon only shows up in "All Search Results" and not in the grouped results.

We don't need a wireframe, use your best judgement. Provide a screenshot.

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #1053 

Companion pul_solr PR: https://github.com/pulibrary/pul_solr/pull/352

Screen Shot 2022-09-23 at 12 06 31 PM

Screen Shot 2022-09-23 at 12 07 32 PM

### CODE REVIEW

**Comment by hackartisan** [comment]
Thank you for the screenshots! Just from those I'm thinking we need to also update the color of the little label / badge thingie as well as the wording. 

See the badges on https://xd.adobe.com/view/1a8defd5-0cd8-4715-a5c1-9cb7795d2ece-4fde/screen/2aeefae6-aee7-4ec5-929a-64f600503129 and https://xd.adobe.com/view/1a8defd5-0cd8-4715-a5c1-9cb7795d2ece-4fde/screen/84261189-8278-4c7e-9c84-64d6f00c5bff. @sdellis are "Has online content" (in green) and "Child records have online content" (in grey) the final approved design? I also notice some capitalization inconsistencies in the wireframes which I'm not sure what to say about.

**Comment by eliotjordan** [comment]
If the badges should be different color, please let me know the hex values and I'll make the updates.

**Comment by hackartisan** [comment]
Also I think we talked about having the online content tag / label / thingie be on the same line as the other little tag / badges? Here's a screenshot of how they look in staging, above the other ones. @sdellis ?

Screen Shot 2022-09-23 at 2 26 14 PM

**Review by hackartisan — CHANGES_REQUESTED** [review]
It looks great. Blocking on the above design questions.

**Comment by eliotjordan** [comment]
> For the icon, you can use #636363 both on the TOC and the badge (same value for parent badge text). You can use #E3E0E0 for the bg of the parent badge. And you can use #C7C4C4 for the badge outline.

**Comment by eliotjordan** [comment]
Fixed and ready for re-review:
Screen Shot 2022-09-26 at 11 08 32 AM

**Comment by eliotjordan** [comment]
@sdellis Can you please fill in the correct values:

SOME ONLINE CONTENT
color: 
background-color:
border-color:

HAS ONLINE CONTENT:
color: 
background-color:
border-color:

Currently the online content icon has a single color: #636363. Is this correct?

**Comment by eliotjordan** [comment]
Ready for re-review:
Screen Shot 2022-09-26 at 2 15 00 PM

**Review by hackartisan — APPROVED** [review]
👍🏻 I created #1172 to follow up on the placement of the badges.

**Pull request merged**
