### PR TITLE
Search by EADID & Box/Folder Number

### LINKED ISSUE #116: Ability to search by box number and/or box and folder number
Staff often know the collection code and box and/or folder numbers, so being able to search by them saves time compared to finding a collection and then navigating to the box/folder. Indexing some combined format "C1234_box12" or "C1234_box12_folder2" so staff can accurately search by these numbers would help make that work smoothly.

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #116

Related to pulibrary/pul_solr#241

### CODE REVIEW

**Comment by tpendragon** [comment]
CI is failing because the docker image doesn't have the new config. I'll fiddle with it in the morning.

**Comment by hackartisan** [comment]
These solr config changes will also need to go into pul_solr

**Comment by tpendragon** [comment]
@hackartisan I think they already are, in pulibrary/pul_solr#241, unless I missed something.

**Comment by hackartisan** [comment]
@tpendragon oh! Thanks. Not sure why I didn't get a github alert for that one.

**Review by hackartisan — APPROVED** [review]

**Pull request merged**
