### PR TITLE
Improve mobile responsiveness

### PR DESCRIPTION
**Pull request by thanyabegum**
Advances #111 

### Left align homepage headings instead of justifying
Before
Screen Shot 2022-09-21 at 2 54 30 PM

After
Screen Shot 2022-09-21 at 2 54 21 PM

### Fix overflow of collection content list
Before
Screen Shot 2022-09-21 at 2 57 10 PM

After
Screen Shot 2022-09-21 at 2 57 55 PM

### Fix bottom toolbar stickiness and wrapping
Before
Screen Shot 2022-09-21 at 3 44 57 PM

After
Screen Shot 2022-09-21 at 3 45 09 PM

### Stop autocomplete options from being cutoff
Before
Screen Shot 2022-09-21 at 3 04 19 PM

After
Screen Shot 2022-09-21 at 3 04 06 PM

### CODE REVIEW

**Comment by hackartisan** [comment]
@thanyabegum can you add some screenshots for the fixes made in this PR? before / after screenshots would be especially helpful!

**Comment by thanyabegum** [comment]
> @thanyabegum can you add some screenshots for the fixes made in this PR? before / after screenshots would be especially helpful!

You're right! Just added some before and after screenshots.

**Comment by hackartisan** [comment]
Thank you! for the bottom toolbar screenshots, it looks like the value for the "title" field is still covered up in the "after" screenshot -- is that just because it's not scrolled down all the way?

**Comment by thanyabegum** [comment]
> Thank you! for the bottom toolbar screenshots, it looks like the value for the "title" field is still covered up in the "after" screenshot -- is that just because it's not scrolled down all the way?

Yup, it's not scrolled down all the way. I just updated those sets of screenshots to better reflect how the new bottom toolbar doesn't cut off the content list.

**Review by sdellis — APPROVED** [review]
This looks great, @thanyabegum ! Nice work!

**Pull request merged**
