### PR TITLE
Create research help page

### LINKED ISSUE #368: Integrate a static "Help" section into the site
There should be created a static Help page which users should be able to readily access, and this content should be maintained within the PULFALight application itself. Please note that the users should be able to regularly update the content.

### PR DESCRIPTION
**Pull request by hackartisan**
Populate it with initial content
And link to it from home

closes #368

### CODE REVIEW

**Comment by hackartisan** [comment]
screen shots:
Screen Shot 2020-11-10 at 2 34 21 PM
Screen Shot 2020-11-10 at 2 40 28 PM

**Comment by hackartisan** [comment]
lol oops I left the "this is like the research blog" text. let me fix that.

**Comment by hackartisan** [comment]
fixed; this is ready for review.

**Review by eliotjordan — APPROVED** [review]

**Comment by ccleeton** [comment]
@hackartisan -- For the Statement on AV Materials. Could this link directly to https://library.princeton.edu/special-collections/services/digitization-publication-services and then have no text in the drop down?

We are still working on a more detailed policy and it seems it would be easier to link to the website and make our changed there when needed. 
@faithc PS approved this change

**Comment by hackartisan** [comment]
@ccleeton Yep, I'll open a new issue for this

**Pull request merged**
