### PR TITLE
Add Collection-Level Storage Note

### LINKED ISSUE #225: Implement collection-level "Storage Note"
There are several notes whose labels and text strings are currently auto-generated via the production stylesheet for the current site (which @sdellis and @regineheberlein know about), including physloc type="code," which displays as the Storage note on the current site (https://findingaids.princeton.edu/collections/C0187/#summary), and prefercite, which displays as Credit this material on pulfa 2.0: https://findingaids.princeton.edu/collections/C0187/#accessuse. 

The Physical Location note on pulfalight is currently displaying the attribute value: https://pulfalight-staging.princeton.edu/catalog/C0187, which in this case is hsvm.

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #225

### CODE REVIEW

**Review by hackartisan — CHANGES_REQUESTED** [review]
It seems good, but I don't really understand why we want to run the field through a presenter as part of indexing. Wouldn't it make more sense to compute the value at display time, so that when these notes change we don't have to reindex everything?

**Comment by tpendragon** [comment]
Yup, good call, not sure what I was thinking. Thanks!

**Comment by tpendragon** [comment]
@hackartisan Should be good for re-review.

**Review by hackartisan — APPROVED** [review]

**Comment by hackartisan** [comment]
Thanks!

**Pull request merged**
