### PR TITLE
Add link to Ask us a Question for repository contact.

### LINKED ISSUE #625: Repository info: email address is wonky
Are the email addresses supposed to be spelled out as such: https://findingaids-beta.princeton.edu/?f%5Bcollection_sim%5D%5B%5D=&f%5Brepository_sim%5D%5B%5D=Manuscripts+Division&group=true&q=brendan+behan&search_field=all_fields?

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #625

Screen Shot 2021-01-28 at 2 05 32 PM

### CODE REVIEW

**Comment by ccleeton** [comment]
This is great, honestly looks alot better than the previous!!! Thanks!

**Comment by sdellis** [comment]
@ccleeton Using the "Ask Us" form on the SC website takes the user away from Finding Aids. I believe this would be better if we used the Finding Aids "Ask A Question" form that shows up as a pop up, but this seems to be progress, so I won't hold it up.

**Review by sdellis — APPROVED** [review]

**Comment by ccleeton** [comment]
@sdellis Is the Finding Aids Ask a Question going to the libanswers queue?

**Comment by sdellis** [comment]
@ccleeton PULFA 2.0 or PulfaLight? Are you not getting emails that you expect to be receiving in that queue?

**Comment by ccleeton** [comment]
@sdellis Pulfalight, I haven't submitted anything I just wasn't sure where they were going.

**Pull request merged**
