### PR TITLE
Index "combined" fields as text rather than strings

### LINKED ISSUE #1159: scopecontent_combined_ssm field is too large
Might need to trunctate during indecxing.

```
Exception writing document id C0171 to the index; possible analysis error: DocValuesField "scopecontent_combined_ssm" is too large, must be <= 32766
```

## Backtrace

    line 60 of [PROJECT_ROOT]/app/jobs/aspace_index_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/88665120)

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #1159

Related pul_solr PR: https://github.com/pulibrary/pul_solr/pull/354

### CODE REVIEW

**Comment by tpendragon** [comment]
Won't this break the display of that collection? It'll try to parse that JSON and fail?

**Comment by eliotjordan** [comment]
@tpendragon I honestly don't know what the point of these combined fields is. They don't seem to be used for anything and truncating the json doesn't beak the display.

https://findingaids-staging.princeton.edu/catalog/C0171

**Comment by eliotjordan** [comment]
One solution is to change the type of the field to `text`, but again, I can't tell how these combined fields are used.

**Comment by tpendragon** [comment]
I think they're used for the headings display, added in this PR: https://github.com/pulibrary/pulfalight/pull/1134/files

**Comment by eliotjordan** [comment]
Tested in staging. C0171 (with a large scopecontent value) indexes fine.

Check `scopecontent_combined_tsm`:
https://findingaids-staging.princeton.edu/catalog/C0171/raw

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
