### PR TITLE
Content Warnings should inherit, but not scopecontent. 

### LINKED ISSUE #1237: Collection-level content warning scope note should inherit down
Like other collection-level notes, scopecontent notes with the label "content warning" should inherit down unless superseded by a lower-level note. See for example: https://findingaids.princeton.edu/catalog/TC040 

https://findingaids.princeton.edu/catalog/TC040_c00002 should have the content warning from https://findingaids.princeton.edu/catalog/TC040_c00001

## Sudden Priority Justification

Without this, our researchers will not be appropriately warned about potentially harmful content.

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #1237

### CODE REVIEW

**Review by eliotjordan — APPROVED** [review]

**Comment by eliotjordan** [comment]
@tpendragon Just needs a rebase.

**Comment by tpendragon** [comment]
@eliotjordan Rebased.

**Comment by eliotjordan** [comment]
@tpendragon Something's amiss after that rebase. Maybe just need to re-add TC040?

**Comment by tpendragon** [comment]
Yup, lost a commit in there.

**Pull request merged**
