### PR TITLE
Index unpublished EADs, don't make them discoverable.

### LINKED ISSUE #1010: Figgy should synchronize finding aid data that hasn't yet been published in aspace
proxy for pulibrary/figgy#5050

### PR DESCRIPTION
**Pull request by tpendragon**
This allows Figgy to hit the JSON endpoints for non-discoverable resources, but doesn't show them in search results or the HTML/Raw routes.

Closes #1010
Closes pulibrary/figgy#5050

Ansible PR: https://github.com/pulibrary/princeton_ansible/pull/2990

### CODE REVIEW

**Review by hackartisan — APPROVED** [review]
👍🏻

**Comment by tpendragon** [comment]
Drafting this until there's an auth token required to view private materials.

**Comment by tpendragon** [comment]
This should be ready for review again, working on the accompanying ansible PR

**Review by hackartisan — APPROVED** [review]
looks great!

**Pull request merged**
