### PR TITLE
Add harmful language button to components

### LINKED ISSUE #1064: Add report harmful content button to every component

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #1064 

Screen Shot 2022-05-06 at 4 18 27 PM
Screen Shot 2022-05-06 at 4 20 01 PM

### CODE REVIEW

**Comment by escowles** [comment]
I want to make sure we're talking about harmful *language* and not harmful *content* — we've talked about both and have two different (but obviously related) statements on the Library main website:

* https://library.princeton.edu/statement-harmful-content
* https://library.princeton.edu/about/languagestatement

in addition to the statement on language in Pulfalight:
* https://findingaids.princeton.edu/archival_language

The user-visible UI says "harmful language" but the branch name, etc. says "harmful content", so I'm confused about which one we're talking about here, or if we should create a combined page since users may not differentiate between these two cases anyway.

**Review by sdellis — COMMENTED** [review]
@tpendragon this looks great, but I'm trying to get the icons aligned better. A bug in LUX that can't be fixed until that's upgraded is making this more difficult. I'm working on that this morning.

**Comment by tpendragon** [comment]
> The user-visible UI says "harmful language" but the branch name, etc. says "harmful content

I'm just bad at branch names. It's harmful language.

**Review by hackartisan — APPROVED** [review]
looks nice!

**Pull request merged**
