### PR TITLE
Change image on front page

### PR DESCRIPTION
**Pull request by bess**
Use the image of Firestone special collections from ticket #661
Position so as much as possible the students are not covered by
the search box.

Here are some screen shots at different widths:

Screen Shot 2021-02-25 at 2 17 14 PM

Screen Shot 2021-02-25 at 2 17 51 PM

### CODE REVIEW

**Comment by tpendragon** [comment]
I'm pretty surprised this passes the accessibility tests. Seems like we need some way to better see the title text. Maybe a darkened opacity on the image? Any suggestions @sdellis?

**Comment by bess** [comment]
Good point. I'll try adding some opacity to the image.

**Comment by bess** [comment]
Here it is with an opacity of .3 on the image, and I swapped the h1 color to be $black-pul. 

Screen Shot 2021-02-25 at 3 32 02 PM

**Comment by ccleeton** [comment]
I like this with the opacity!

**Comment by tpendragon** [comment]
I find it pretty hard to read the text with so much going on behind it, but I have no good suggestions for how to improve that. It might just be a personal problem too.

**Comment by sdellis** [comment]
@tpendragon I think that darkening the image, keeping the white lettering, and adding a drop shadow should do the trick. I'm happy to give it a try if it helps.

**Comment by bess** [comment]
@sdellis Would you please give that a shot? It sounds like your UI skills vastly exceed mine. Thank you!

**Comment by sdellis** [comment]
HOMEPAGE WITH DROPSHADOW

Here's a version with a darkened image, dropshadow, and centering of text.

**Comment by sdellis** [comment]
FYI - axe is not taking the shadow into consideration in its test. This is perfectly acceptable with regard to accessibility though. See: https://www.w3.org/TR/WCAG20-TECHS/G18.html

> If the background or the letters vary in relative luminance (or are patterned) then the background around the letters can be chosen or shaded so that the letters maintain a 4.5:1 contrast ratio with the background behind them even if they do not have that contrast ratio with the entire background.

**Comment by tpendragon** [comment]
@sdellis @bess Just need rubocop run, I think.

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
